apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-1
  labels:
    app: sample-app-123
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app-123
  template:
    metadata:
      labels:
        app: sample-app-123
    spec:
      containers:
      - name: busybox123
        image: busybox
        command: ["sh", "-c", "while true; do date; echo 'Hello from deployment 1'; sleep 60; done"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "120Mi"
            cpu: "120m"
      restartPolicy: Always

